### PR TITLE
added merakiscans

### PR DESCRIPTION
**Pull request by MammothJerk**
not sure im doing these pull requests correctly but just add 
`// @match *://merakiscans.com/*/*`
and 
`match: "^https?://(mngcow|mangadoom|mangaindo|merakiscans|www\\.3asq|moonbunnycafe)\\.(co|id|info|com)/[^/]+/[0-9.]+",`

### CODE REVIEW

**Comment by fuzetsu** [comment]
Looks like this merge request has gotten a bit mixed up. The simplest thing to do would probably be to start fresh, take the current version of the master branch on this repository, and simply add what you want and then submit it. It seems like it has various changes from other branches or something. 

Also no need to update the version number as I'll do that once I'm ready to push a new version.

**Comment by MammothJerk** [comment]
Alright thanks, ill try again and hope it works correctly

**Comment by fuzetsu** [comment]
👍  thanks for contributing!

**Comment by fuzetsu** [comment]
closed in favor of #22

**Pull request closed without merging**
